# $OpenBSD$

COMMENT =	OAuth 2.0 client library

DISTNAME =	oauth2client-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	http://github.com/google/oauth2client/

# Apache 2.0
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

FLAVORS =	python3
FLAVOR ?=

MODPY_EGG_VERSION =	4.1.1

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
