# $OpenBSD$

COMMENT =	tool for communicating with pebbles

GH_ACCOUNT =	pebble
GH_PROJECT =	pebble-tool
GH_COMMIT =	8b4771bbd7f8dacc8cbe776aaaf0aa704e152f9f

DISTNAME =	${GH_PROJECT}-2017.06.07

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/pebble/pebble-tool

# MIT
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

FLAVOR ?=
FLAVORS =	python3

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
