# $OpenBSD$

# original: A Python Progressbar library to provide visual (yet text based) progress to long running operations.
COMMENT =	Python Progressbar library to provide visual (yet text

DISTNAME =	progressbar2-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/WoLpH/python-progressbar

# BSD
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

FLAVORS =	python3
FLAVOR ?=

MODPY_EGG_VERSION =	3.30.2

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
