# $OpenBSD: Makefile,v 1.1.1.1 2014/11/01 20:46:24 abieber Exp $

COMMENT =		easy, secure backup program

VERSION =		1.9
DISTNAME =		obnam-${VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		sysutils

HOMEPAGE =		http://obnam.org/

# GPLv3
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =		http://deftly.net/

MODULES =		lang/python

MODPY_SETUPTOOLS =	Yes

NO_TEST =		Yes

.include <bsd.port.mk>
