# $OpenBSD$

# original: Python Utils is a module with some convenient utilities not included with the standard Python install
COMMENT =	Python Utils is a module with some convenient utilities not

DISTNAME =	python-utils-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/WoLpH/python-utils

# BSD
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

MODPY_EGG_VERSION =	2.1.0

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
