# $OpenBSD$

COMMENT =	Pure Python PNG image encoder/decoder

DISTNAME =	pypng-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/drj11/pypng

# license field not set, consider bugging module's author
PERMIT_PACKAGE_CDROM =	unknown license
PERMIT_PACKAGE_FTP =	unknown license
PERMIT_DISTFILES_FTP =	unknown license

MODULES =		lang/python

FLAVORS =	python3
FLAVOR ?=

MODPY_EGG_VERSION =	0.0.18

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
