# $OpenBSD$

COMMENT =	console carddav client

DISTNAME =	khard-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/scheibler/khard/

MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

# unknown license -> 'GPL'
PERMIT_PACKAGE_CDROM =	unknown license
PERMIT_PACKAGE_FTP =	unknown license
PERMIT_DISTFILES_FTP =	unknown license

RUN_DEPENDS =		textproc/py-vobject,python3

MODULES =		lang/python

MODPY_EGG_VERSION =	0.11.4

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
