.\"     $OpenBSD: goland.1,v 1.1 2018/05/27 17:09:44 rsadowski Exp $
.Dd $Mdocdate: May 27 2018 $
.Dt GOLAND 1
.Os
.Sh NAME
.Nm goland
.Nd launch GoLand Go Integrated Development Environment
.Sh SYNOPSIS
.Nm
.Op jvm-args
.Sh DESCRIPTION
.Nm
starts up the JetBrains GoLand Go Integrated Development Environment.
.Sh SEE ALSO
The web site
.Lk https://www.jetbrains.com/go/ .
