# $OpenBSD: Makefile,v 1.1.1.1 2013/04/30 14:54:46 abieber Exp $

COMMENT =	get number of occupied columns of a string on terminal

MODULES =	cpan
DISTNAME =	Text-CharWidth-0.04
CATEGORIES =	sysutils

SHARED_LIBS=	CharWidth	0.0

MAINTAINER =	Aaron Bieber <abieber@openbsd.org>

MASTER_SITES =	http://search.cpan.org/CPAN/authors/id/K/KU/KUBOTA/

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
