# $OpenBSD$

COMMENT =	Cross-platform colored terminal text

DISTNAME =	colorama-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/tartley/colorama

# BSD
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

FLAVORS =	python3
FLAVOR ?=

MODPY_EGG_VERSION =	0.3.9

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
