# $OpenBSD$

# original: Plugin for the music library manager Beets. Follow artists from your library using muspy.com
COMMENT =	Plugin for the music library manager Beets. Follow artists

DISTNAME =	beets-follow-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/nolsto/beets-follow

# MIT
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

MODPY_EGG_VERSION =	1.0.0

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
