# $OpenBSD$

COMMENT =	Library for communicating with pebbles over pebble protocol

DISTNAME =	libpebble2-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/pebble/libpebble2

# MIT
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

FLAVORS =	python3
FLAVOR ?=

MODPY_EGG_VERSION =	0.0.26

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
