# $OpenBSD: Makefile,v 1.8 2014/04/28 20:52:13 edd Exp $

COMMENT =		network address representation and manipulation library

MODPY_EGG_VERSION =	0.7.12
DISTNAME =		netaddr-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		net

HOMEPAGE =		http://github.com/drkjam/netaddr/

# MIT
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =		${MASTER_SITE_PYPI:=n/netaddr/}

MODULES =		lang/python

#MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
