# $OpenBSD$

COMMENT =	Core utilities for Python packages

DISTNAME =	packaging-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/pypa/packaging

# unknown license -> 'BSD or Apache License, Version 2.0'
PERMIT_PACKAGE_CDROM =	unknown license
PERMIT_PACKAGE_FTP =	unknown license
PERMIT_DISTFILES_FTP =	unknown license

MODULES =		lang/python

FLAVORS =	python3
FLAVOR ?=

MODPY_EGG_VERSION =	16.8

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
