# $OpenBSD$

COMMENT =	pomodoro widget

MODGO_MODNAME =	github.com/tomsquest/fynodoro
MODGO_VERSION =	v1.7.0

DISTNAME =	fynodoro-${MODGO_VERSION}

CATEGORIES =	productivity

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/go

.include "modules.inc"

.include <bsd.port.mk>
