# $OpenBSD: Makefile.template,v 1.76 2017/02/25 16:04:20 danj Exp $

COMMENT =	snapshot upgrade tool

GH_ACCOUNT =	qbit
GH_PROJECT =	snap
GH_TAGNAME =	1.1.2

CATEGORIES =	sysutils

HOMEPAGE =	https://github.com/qbit/snap

MAINTAINER =		Aaron Bieber <abieber@openbsd.org>

# ISC
PERMIT_PACKAGE_CDROM =	Yes

MAKE_ENV =              BINDIR=${LOCALBASE}/bin \
                        MANDIR=${LOCALBASE}/man/man


.include <bsd.port.mk>
