# $OpenBSD: Makefile,v 1.9 2013/03/10 22:55:05 espie Exp $

COMMENT =		pykka is a python implementation of the actor model

MODPY_EGG_VERSION =	1.2.0
DISTNAME =		Pykka-${MODPY_EGG_VERSION}
PKGNAME =		py-pykka-${MODPY_EGG_VERSION}
CATEGORIES =		devel

HOMEPAGE =		https://pypi.python.org/pypi/Pykka/

MAINTAINER =		Aaron Bieber <abieber@openbsd.org>

# Apache
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =		${MASTER_SITE_PYPI:=P/Pykka/}

MODULES =		lang/python

NO_TEST =		Yes

.include <bsd.port.mk>
