# $OpenBSD: Makefile,v 1.19 2015/09/12 05:36:17 rpointel Exp $

COMMENT =		system for sequential logic synth

DISTNAME =		abc-2015.09.09

CATEGORIES =		devel

HOMEPAGE =		http://www.eecs.berkeley.edu/~alanmi/abc/

MAINTAINER =		Aaron Bieber <abieber@openbsd.org>

MASTER_SITES =		https://deftly.net/

# BSD?
PERMIT_PACKAGE_CDROM =	Yes

USE_GMAKE = 		Yes

.include <bsd.port.mk>
