# $OpenBSD$

COMMENT =	generate markdown documentation for Go code

MODGO_MODNAME =	github.com/princjef/gomarkdoc
MODGO_VERSION =	v0.3.1

DISTNAME =	gomarkdoc-${MODGO_VERSION}

CATEGORIES =	devel

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/go

.include "modules.inc"

.include <bsd.port.mk>
