# $OpenBSD: Makefile,v 1.11 2015/04/02 14:21:14 jasper Exp $

COMMENT =	modestmaps for python

MODPY_EGG_VERSION = 1.4.6

DISTNAME =	ModestMaps-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	geo

HOMEPAGE =	http://pypi.python.org/pypi/ModestMaps

# BSD
PERMIT_PACKAGE_CDROM =	Yes

MODPY_PI =	Yes

MODULES =	lang/python

#MODPY_SETUPTOOLS = Yes

NO_TEST =	Yes

.include <bsd.port.mk>
