# $OpenBSD$

COMMENT =	extremely fast JavaScript bundler

MODGO_MODNAME =	github.com/evanw/esbuild
MODGO_VERSION =	v0.14.14

DISTNAME =	esbuild-${MODGO_VERSION}

CATEGORIES =	devel

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/go

MODGO_MODULES =	\
	golang.org/x/sys	 v0.0.0-20210908233432-aa78b53d3365

.include <bsd.port.mk>
