COMMENT =	tool for managing secrets

MODGO_MODNAME =	go.mozilla.org/sops/v3
MODGO_VERSION =	v3.7.3

DISTNAME =	sops-${MODGO_VERSION}

CATEGORIES =	security

# MPL-2
PERMIT_PACKAGE =	Yes

WANTLIB += c pthread

MODULES =		lang/go

.include "modules.inc"
.include <bsd.port.mk>
