# $OpenBSD: Makefile,v 1.21 2014/06/14 23:26:01 sthen Exp $

COMMENT=	get, unpack build and install modules from CPAN

MODULES=	cpan
DISTNAME=	App-cpanminus-1.7014

CATEGORIES=	sysutils

# perl
PERMIT_PACKAGE_CDROM=	Yes

#TEST_IS_INTERACTIVE=	Yes

.include <bsd.port.mk>
