# $OpenBSD$

# original: A QR code generator written purely in Python with SVG, EPS, PNG and terminal output.
COMMENT =	QR code generator written purely in Python with SVG, EPS,

DISTNAME =	PyQRCode-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/mnooner256/pyqrcode

# BSD
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		lang/python

FLAVORS =	python3
FLAVOR ?=

MODPY_EGG_VERSION =	1.2.1

MODPY_PI =		Yes

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
