COMMENT =	session manager and task runner for tmux

MODGO_MODNAME =	github.com/ivaaaan/smug
MODGO_VERSION =	v0.3.3

DISTNAME =	smug-${MODGO_VERSION}

CATEGORIES =	sysutils

# MIT
PERMIT_PACKAGE =	yes

MODULES =		lang/go

MODGO_MODULES =	\
	github.com/spf13/pflag	 v1.0.5 \
	gopkg.in/check.v1	 v0.0.0-20161208181325-20d25e280405 \
	gopkg.in/yaml.v2	 v2.4.0

.include <bsd.port.mk>
